namespace EmailAgent.Services;

/// <summary>
/// Abstraction over the Azure AI Foundry agent that processes incoming emails
/// and generates a reply using knowledge from Azure AI Search (SharePoint + Blob Storage).
/// </summary>
public interface IAIAgentService
{
    /// <summary>
    /// Sends the email content to the AI agent and returns the generated reply text.
    /// </summary>
    /// <param name="subject">Subject line of the email.</param>
    /// <param name="bodyText">Body text of the email.</param>
    /// <param name="senderName">Display name of the sender.</param>
    /// <param name="senderAddress">SMTP address of the sender.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The reply body generated by the agent.</returns>
    Task<string> ProcessEmailAsync(
        string subject,
        string bodyText,
        string senderName,
        string senderAddress,
        CancellationToken cancellationToken = default);
}
